@baseUrl = http://localhost:3333
@UrlToken = {{authenticate.response.body.access_token}}

###

# @name create-account
POST {{baseUrl}}/auth/signup
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

{
    "name": "teste",
    "email": "teste123@ghmail.com",
    "password": "afawfwafwa",
    "lastname":  "silva",
    "phone": "1123456789"
}

###

# @name authenticate
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "name": "teste",
  "email": "teste123@ghmail.com",
  "password": "afawfwafwa"
}

###

# @name FindAllUsers
GET  {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

###

# @name FindUserById
GET {{baseUrl}}/users/f5efd8c7-01b7-415f-a053-e4b11098f1b0
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

###

# @name updateUser
PATCH {{baseUrl}}/users/46fff8d6-e5e8-4833-a59b-ab3519ec0988
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

{
    "name": "Lucas Maia",
    "email": "LUCASmaia3123@ghmail.com",
    "password": "nfienesiofn",
    "lastname":  "silva",
    "phone": "23432444343242",
    "role": "admin"
}

###

# @name DeleteUser
DELETE  {{baseUrl}}/users/e9781ce0-8355-4e3a-b358-d8c05be98cad
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

###

# @name create-family
POST {{baseUrl}}/family
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

{
    "user": "family1",
    "amountPeople": 40,
    "phone": "11948955365",
    "cpf": "12345678910",
    "familyIncome": 40,
    "foodStamps": 40
}

###

# @name FindAllFamily
GET  {{baseUrl}}/family
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

###

# @name FindFamilyById
GET {{baseUrl}}/family/12345678910
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

###

PATCH {{baseUrl}}/family/12345678910
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

{
    "user": "Carina Peres",
    "amountPeople": 20,
    "phone": "11948955365",
    "cpf": "12345648910",
    "familyIncome": 20,
    "foodStamps": 60
}

###

DELETE {{baseUrl}}/family/c81443c5-897f-4c09-96a5-1902f8fa5520
Content-Type: application/json
Authorization: Bearer {{UrlToken}}


### Stock

# @name create-stock
POST {{baseUrl}}/stock
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

{
    "name": "Blusa Preta",
    "type": "roupa",
    "quantity": 3,
    "size":  "GG",
    "availability": 54
}

###

# @name FindAllStock
GET  {{baseUrl}}/stock
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

###

# @name FindStockById
GET {{baseUrl}}/stock/7d353708-2b07-4ed5-90f0-e8ea13a84b3d
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

###

PATCH {{baseUrl}}/stock/7d353708-2b07-4ed5-90f0-e8ea13a84b3d
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

{
    "name": "Blusa Amarela",
    "type": "roupa",
    "quantity": 5,
    "size":  "G",
    "availability": 56
}

###

DELETE {{baseUrl}}/stock/fab5fdb0-d316-4b8b-abbc-e4af6a3c07a8
Content-Type: application/json
Authorization: Bearer {{UrlToken}}

